# azure-pipelines.yml
trigger:
- main

pr:
- main

jobs:
- job: Terraform
  displayName: 'Deploy Terraform Configuration'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseTerraform@0
    inputs:
      terraformVersion: '1.4.x'

  - script: |
      terraform init
    displayName: 'Terraform Init'

  - script: |
      terraform plan
    displayName: 'Terraform Plan'

  - script: |
      terraform apply -auto-approve
    displayName: 'Terraform Apply'
